#ifndef _H_hardware_h
#define _H_hardware_h

#include "msp430hardware.h"

// LEDs
TOSH_ASSIGN_PIN(RED_LED, 2, 0); //changed from 5, 4
TOSH_ASSIGN_PIN(GREEN_LED, 2, 1); //changed from 5, 5
TOSH_ASSIGN_PIN(YELLOW_LED, 2, 2); //changed from 5, 6
TOSH_ASSIGN_PIN(PINK_LED, 2,3); //1,1 for P11_PWM

// SPI pins
TOSH_ASSIGN_PIN(SOMI0, 3, 5);
TOSH_ASSIGN_PIN(SIMO0, 3, 4);
TOSH_ASSIGN_PIN(UCLK0, 3, 3);
TOSH_ASSIGN_PIN(ENRF0, 4, 6);


//UART pins
TOSH_ASSIGN_PIN(UTXD0, 3, 4);
TOSH_ASSIGN_PIN(URXD0, 3, 5);
TOSH_ASSIGN_PIN(UTXD1, 3, 6);
TOSH_ASSIGN_PIN(URXD1, 3, 7);
TOSH_ASSIGN_PIN(UCLK1, 5, 3);
TOSH_ASSIGN_PIN(SOMI1, 5, 2);
TOSH_ASSIGN_PIN(SIMO1, 5, 1);

#endif // _H_hardware_h
